### ISSUE TITLE
lutorpy + memoize 

### ISSUE THREAD

**Issue by kemelmi** [imodpasteur/lutorpy#11]
Hello

I am using lutorpy and it's great. One issue is that each "require" take a long time (since I run the same script many times). I would like to cache it, i.e., load once and use for all runs. 

0) Have you tried to cache with lutorpy?
1) is it possible to speed up "require" somehow?
2) have you worked with loadcaffe (it also takes too long) with lutorpy
3) can lutorpy work with memoize? e.g., https://wiki.python.org/moin/PythonDecoratorLibrary

Thanks!

**Comment by oeway** [comment]
I just did a quick test with ipython, it's around 5ms to require a module, is it seems very slow for you?
For the first time, it's spend 7 times slower, but after it's fast:

``` python
In [1]: import lutorpy                                                                                      
In [2]: %timeit require('nn')                                                                               
The slowest run took 6.83 times longer than the fastest. This could mean that an intermediate result is being cached. 100 loops, best of 3: 5.64 ms per loop                                                                      
In [3]: %timeit require('nn')                                                                               
100 loops, best of 3: 5.15 ms per loop                                                                      
In [4]: %timeit require('nn')                                                                               
100 loops, best of 3: 5.12 ms per loop                                                                      
In [5]: %timeit require('loadcaffe')                                                                        
100 loops, best of 3: 5.45 ms per loop                                                                      
In [6]: %timeit require('loadcaffe')                                                                        
100 loops, best of 3: 5.38 ms per loop 
```

I also did a test in torch, it takes 1ms per require:

``` lua
timer = torch.Timer()
for i=1,1000 do
  require "loadcaffe"
end
print('Time elapsed for 1,000 times: ' .. timer:time().real .. ' seconds')
-- output: Time elapsed for 1,000 times: 1.1470279693604 seconds
```

So, it's like 5~6 times slower for require, but if you run some torch module or training with torch, it should be the same speed as torch, because lutorpy is just like a wrapper.

All the test is done on Ubuntu 14.04 with the standard torch installation.
Could you run the same test and see how much slow it is?

**Comment by kemelmi** [comment]
I just checked that require("cudnn") takes 1.5 seconds which is the key issue.

**Comment by kemelmi** [comment]
And I run the script many times, i.e., run require many times.

**Comment by oeway** [comment]
Can you try it in torch, if torch require is similar, then I would say it's nothing to do with lutorpy.

**Comment by ProGamerGov** [comment]
How did you get `loadcaffe` to work with luatorpy? 

This is the error I'm getting: 


```
python test2.py
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Traceback (most recent call last):
  File "test2.py", line 22, in <module>
    cnn = loadcaffe.load(params.proto_file, params.model_file).type(dtype)
  File "lutorpy/_lupa.pyx", line 562, in lutorpy._lupa._LuaObject.__call__ (lutorpy/_lupa.c:9459)
  File "lutorpy/_lupa.pyx", line 1658, in lutorpy._lupa.call_lua (lutorpy/_lupa.c:25877)
  File "lutorpy/_lupa.pyx", line 1665, in lutorpy._lupa.execute_lua_call (lutorpy/_lupa.c:25968)
  File "lutorpy/_lupa.pyx", line 281, in lutorpy._lupa.LuaRuntime.reraise_on_exception (lutorpy/_lupa.c:5526)
  File "lutorpy/_lupa.pyx", line 1901, in lutorpy._lupa.py_object_getindex_with_gil (lutorpy/_lupa.c:28830)
  File "lutorpy/_lupa.pyx", line 1863, in lutorpy._lupa.getitem_for_lua (lutorpy/_lupa.c:28129)
TypeError: 'type' object has no attribute '__getitem__'
```

Edit: 

The issue was the dytpe code:

```
use_cuda = torch.cuda.is_available()
dtype = torch.cuda.FloatTensor if use_cuda else torch.FloatTensor
cnn = loadcaffe.load(params.proto_file, params.model_file) #.type(dtype)
```

Because this works: 

```
#use_cuda = torch.cuda.is_available()
#dtype = torch.cuda.FloatTensor if use_cuda else torch.FloatTensor
cnn = loadcaffe.load(params.proto_file, params.model_file) #.type(dtype)
```

**Comment by oeway** [comment]
@ProGamerGov Try to use `._type(dtype)` instead of `.type(dtype)`, in lutorpy everything you do with `:` in lua should be converted into `._`.

**Comment by ProGamerGov** [comment]
@oeway Would I then have to do everything else with Lua modules? Or will the model work normally with PyTorch's stuff?

**Comment by oeway** [comment]
Lutorpy is not aiming for pytorch, it’s for lua and torch, however, you can
use numpy as a bridge to transfer data between Lua and pytorch.
