### ISSUE TITLE
Installing lutorpy on OSX with Python 3.5

### ISSUE THREAD

**Issue by alexholdenmiller** [imodpasteur/lutorpy#13]
I know it's not fully supported, so just wanted to document my experience so far.

In short:
1) I couldn't install with pip
2) I could install from source, but a few things weren't compatible with python3, but patching them still couldn't get the runtime to work
3) I installed lupa separately and forced lutorpy to call the external runtime, but that segfaulted

---

Attempt 1: Install with pip.

```
pip3 install lutorpy
Collecting lutorpy
  Using cached lutorpy-1.3.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python3.5/site-packages (from lutorpy)
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python3.5/site-packages (from lutorpy)
Building wheels for collected packages: lutorpy
  Running setup.py bdist_wheel for lutorpy ... error
  Complete output from command /usr/local/opt/python3/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/t7/v4xk5xqj0s7fjfd9x1r92lk58zclp8/T/pip-build-0yyrutkq/lutorpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/t7/v4xk5xqj0s7fjfd9x1r92lk58zclp8/T/tmpcycbonnppip-wheel- --python-tag cp35:
  torch_install: /Users/ahm/local/torch/install
  os family Darwin
  building without Cython
  torch install:/Users/ahm/local/torch/install
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.10-x86_64-3.5
  creating build/lib.macosx-10.10-x86_64-3.5/lutorpy
  copying lutorpy/__init__.py -> build/lib.macosx-10.10-x86_64-3.5/lutorpy
  copying lutorpy/torch_path.py -> build/lib.macosx-10.10-x86_64-3.5/lutorpy
  copying lutorpy/version.py -> build/lib.macosx-10.10-x86_64-3.5/lutorpy
  running build_ext
  building 'lutorpy._lupa' extension
  creating build/temp.macosx-10.10-x86_64-3.5
  creating build/temp.macosx-10.10-x86_64-3.5/lutorpy
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DLUA_COMPAT_ALL -I/Users/ahm/local/torch/install/include -I/Users/ahm/local/torch/install/include/TH -I/usr/local/lib/python3.5/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c lutorpy/_lupa.c -o build/temp.macosx-10.10-x86_64-3.5/lutorpy/_lupa.o -std=c++0x -Wno-unused-function -Wno-unreachable-code -Wno-strict-prototypes
  error: invalid argument '-std=c++0x' not allowed with 'C/ObjC'
  error: command 'clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for lutorpy
  Running setup.py clean for lutorpy
Failed to build lutorpy
Installing collected packages: lutorpy
  Running setup.py install for lutorpy ... error
    Complete output from command /usr/local/opt/python3/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/t7/v4xk5xqj0s7fjfd9x1r92lk58zclp8/T/pip-build-0yyrutkq/lutorpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/t7/v4xk5xqj0s7fjfd9x1r92lk58zclp8/T/pip-2tw3qvot-record/install-record.txt --single-version-externally-managed --compile:
    torch_install: /Users/ahm/local/torch/install
    os family Darwin
    building without Cython
    torch install:/Users/ahm/local/torch/install
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.10-x86_64-3.5
    creating build/lib.macosx-10.10-x86_64-3.5/lutorpy
    copying lutorpy/__init__.py -> build/lib.macosx-10.10-x86_64-3.5/lutorpy
    copying lutorpy/torch_path.py -> build/lib.macosx-10.10-x86_64-3.5/lutorpy
    copying lutorpy/version.py -> build/lib.macosx-10.10-x86_64-3.5/lutorpy
    running build_ext
    building 'lutorpy._lupa' extension
    creating build/temp.macosx-10.10-x86_64-3.5
    creating build/temp.macosx-10.10-x86_64-3.5/lutorpy
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DLUA_COMPAT_ALL -I/Users/ahm/local/torch/install/include -I/Users/ahm/local/torch/install/include/TH -I/usr/local/lib/python3.5/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c lutorpy/_lupa.c -o build/temp.macosx-10.10-x86_64-3.5/lutorpy/_lupa.o -std=c++0x -Wno-unused-function -Wno-unreachable-code -Wno-strict-prototypes
    error: invalid argument '-std=c++0x' not allowed with 'C/ObjC'
    error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/t7/v4xk5xqj0s7fjfd9x1r92lk58zclp8/T/pip-build-0yyrutkq/lutorpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/t7/v4xk5xqj0s7fjfd9x1r92lk58zclp8/T/pip-2tw3qvot-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/t7/v4xk5xqj0s7fjfd9x1r92lk58zclp8/T/pip-build-0yyrutkq/lutorpy/
```

The primary error in question here appears to be `error: invalid argument '-std=c++0x' not allowed with 'C/ObjC'`. I'm not very familiar with C/C++ and had trouble debugging this; in short, I switched to a new strategy...

---

Attempt 2: Install from git source.

`git clone` lutorpy repo, then `python3 setup.py install`

Successfully installs! (Though this may have required some of the steps I did trying to debug attempt 1, which included installing a few things--hard to recall now.)

Open a new tab => import lutorpy gives a few errors related to python3 issues. This I'm able to fix by modifying **init**.py (in git repo + reinstall or in site-packages directly) with the following edits:
- replace `import torch_path` with `import lutorpy.torch_path`
- replace two `has_keys` calls with an equivalent `in` expression

However, now I get the following error:

```
>>> import lutorpy as lua
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/lutorpy-1.3.3-py3.5-macosx-10.10-x86_64.egg/lutorpy/__init__.py", line 71, in <module>
    LuaRuntime()
  File "/usr/local/lib/python3.5/site-packages/lutorpy-1.3.3-py3.5-macosx-10.10-x86_64.egg/lutorpy/__init__.py", line 68, in LuaRuntime
    luaRuntime = lutorpy._lupa.LuaRuntime(*args, **kwargs)
  File "lutorpy/_lupa.pyx", line 231, in lutorpy._lupa.LuaRuntime.__cinit__ (lutorpy/_lupa.c:4642)
lutorpy._lupa.LuaError: Failed to initialise Lua runtime
```

After seeing a few posts about getting lupa properly set up elsewhere, I switched to that.

---

Attempt 3: Install Lupa first

I was able to install lupa through the following steps:
1) install xcode
2) `xcode-select -s '/Applications/Xcode.app/Contents/Developer'`
3) `brew install macvim --with-lua`
4) `git clone` lupa repo
5) cd lupa && python3 setup-py install

Note that the first two steps were necessary for step 3, and step 3 was necessary to solve the "lua.h missing" error that others have experienced as well.

Lupa is successfully installed, and I can run the test examples in lupa like...

```
>>> import lupa
>>> from lupa import LuaRuntime
>>> lua = LuaRuntime(unpack_returned_tuples=True)
>>> lua.eval('1+1')
```

Going back to lutorpy, I try modifying the LuaRuntime function as follows:

```
import lutorpy

def LuaRuntime(*args, **kwargs):
    global luaRuntime
    if not ('zero_based_index' in kwargs):
        kwargs['zero_based_index']=True
    luaRuntime = lutorpy._lupa.LuaRuntime(*args, **kwargs)
    return luaRuntime
```

to

```
import lupa

def LuaRuntime(*args, **kwargs):
    global luaRuntime
    luaRuntime = lupa.LuaRuntime(*args, **kwargs)
    return luaRuntime
```

(with the zero_based_index code removed since the external version of lupa does not recognize it)

This actually successfully launches the runtime, but unfortunately I now get segfaults from the python terminal when I try to use the lutorpy commands (such as lua.require('nn')--just calling require('nn') wasn't recognized as a function), despite lupa working fine on its own.

I'm not sure if there's a different way to get the lupa runtime working within lutorpy. I'd be happy to submit a pull request on the python3 compatibility changes--I believe they should work in python2 as well, but I didn't test it.

I'll continue trying a few things tomorrow, but I wanted to document this for now.

**Comment by oeway** [comment]
I just tried again, lupa can be installed indeed, but the problem is torch still not working with lupa.
I think if you can make lupa work with torch, for example, if you can launch a lupa LuaRuntime and require("nn") for example, it's easy to take the rest.

I would suggest you test further on lupa, as I do, see if it works:

``` python
>>> import lupa
>>> lua = lupa.LuaRuntime()
>>> lua.eval('1+1')
2
>>> lua.require("nn")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lupa/_lupa.pyx", line 274, in lupa._lupa.LuaRuntime.require (lupa/_lupa.c:5114)
  File "lupa/_lupa.pyx", line 1263, in lupa._lupa.call_lua (lupa/_lupa.c:18578)
  File "lupa/_lupa.pyx", line 1272, in lupa._lupa.execute_lua_call (lupa/_lupa.c:18688)
  File "lupa/_lupa.pyx", line 1225, in lupa._lupa.raise_lua_error (lupa/_lupa.c:17998)
lupa._lupa.LuaError: error loading module 'libpaths' from file '/Users/Will/torch/install/lib/lua/5.1/libpaths.so':
    dlopen(/Users/Will/torch/install/lib/lua/5.1/libpaths.so, 6): Symbol not found: _luaL_register
  Referenced from: /Users/Will/torch/install/lib/lua/5.1/libpaths.so
  Expected in: flat namespace
 in /Users/Will/torch/install/lib/lua/5.1/libpaths.so
```

It seems that, torch use it own luajit stuff, the lua you installed is a separate one, so lupa can work, but not with torch. I think we need to figure out how to make lupa use the luajit used by torch, or make torch use the same lua which lupa is using.

I tried to force lupa to recognize torch's luajit, but it still not working and complaining:

```
LuaError: Failed to initialise Lua runtime
```

Which I think related to 

> "If you're building a 64 bit application on OSX which links directly or indirectly against LuaJIT, you need to link your main executable with these flags:
> -pagezero_size 10000 -image_base 100000000
> Also, it's recommended to rebase all (self-compiled) shared libraries which are loaded at runtime on OSX/x64 (e.g. C extension modules for Lua). See: man rebase"

Would be great if you explore further, thanks.

**Comment by alexholdenmiller** [comment]
Thanks for the quick suggestions! I'll try that out.

**Comment by seantrue** [comment]
This sounds like we would need to relink Python? That's a little awkward.
