### ISSUE TITLE
no module named builtins

### ISSUE THREAD

**Issue by Fchaubard** [imodpasteur/lutorpy#3]
```
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lutorpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lutorpy/__init__.py", line 7, in <module>
    import builtins
ImportError: No module named builtins
```

Need to run:
`sudo pip install future`

**Comment by oeway** [comment]
Thanks @Fchaubard , I will put future in setup.py as dependency.
