### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by romawhite47** [imodpasteur/lutorpy#48]
I successfully installed lutorpy but get such error during import.

`Traceback (most recent call last):
  File "demo1.py", line 16, in <module>
    import lutorpy
  File "/root/anaconda2/lib/python2.7/site-packages/lutorpy/__init__.py", line 58, in <module>
    from lutorpy._lupa import *
ImportError: /root/anaconda2/lib/python2.7/site-packages/lutorpy/_lupa.so: undefined symbol: PyFPE_jbuf`

**Comment by romawhite47** [comment]
Fixed.
