### ISSUE TITLE
lua.h not found

### ISSUE THREAD

**Issue by kemelmi** [imodpasteur/lutorpy#8]
I'm following the installation instruction and get this error:
`lutorpy/_lupa.c:299:17: fatal error: lua.h: No such file or directory
`

Was I supposed to update the include, path?

**Comment by oeway** [comment]
Hi,

I suppose your torch is not installed in your home folder "~/torch", please type:
`which th`
And then you will know where is torch installed, and after, please edit the file named luajit.pc, https://github.com/imodpasteur/lutorpy/blob/master/luajit.pc
change the "prefix" in the file from "prefix=~/torch/install" to your torch/install folder path, it should fix your problem.

**Comment by kemelmi** [comment]
Thanks! That works for the install. When I run the example: 
`import lutorpy as lua
`
(in python2) 
I get the following error (looks it still assumes torch install is in my home dir). how do I fix it? Thanks

`sh: /home/kemelmi/torch/install/bin/torch-activate: No such file or directory
Traceback (most recent call last):
  File "test_lutorpy.py", line 9, in <module>
    import lutorpy as lua
  File "/usr/lib64/python2.7/site-packages/lutorpy-1.3-py2.7-linux-x86_64.egg/lutorpy/__init__.py", line 15, in <module>
    lualib = ctypes.CDLL(os.path.expanduser("~") + "/torch/install/lib/libluajit.so", mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/kemelmi/torch/install/lib/libluajit.so: cannot open shared object file: No such file or directory`

**Comment by kemelmi** [comment]
Once I install torch in my ~  I don't get that error (although it's not convenient to have it in ~). But I still get: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lutorpy/__init__.py", line 56, in <module>
    from lutorpy._lupa import *
ImportError: No module named _lupa


```

**Comment by korymath** [comment]
Same errors for me.

**Comment by oeway** [comment]
Sorry for the inconvenience, we will try to address the problem by detecting where is torch installed.
For now it just assume it's installed in home folder.

For no module named _lupa error, could you check #2 , let me know if that solve your problem.
@korymath you may also check #2 if you have the same error.

**Comment by korymath** [comment]
Sorted... but now running into Lua runtime issue:

> > > import lutorpy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg/lutorpy/**init**.py", line 72, in <module>
> > >     LuaRuntime()
> > >   File "/Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg/lutorpy/**init**.py", line 69, in LuaRuntime
> > >     luaRuntime = lutorpy._lupa.LuaRuntime(_args, *_kwargs)
> > >   File "lutorpy/_lupa.pyx", line 231, in lutorpy._lupa.LuaRuntime.__cinit__ (lutorpy/_lupa.c:4642)
> > > lutorpy._lupa.LuaError: Failed to initialise Lua runtime

**Comment by oeway** [comment]
Hi,
Actually, we haven't tested on OSX, it seems you have a similar problem as this one: https://github.com/scoder/lupa/issues/13

Could you try to reinstall with the following command:
`python setup.py install --with-cython --no-luajit`

(You need to install cython first.)

I hope it can be solved, please let me know how you solve the problem, it can help other people using osx as well, thank you.

**Comment by oeway** [comment]
Hey,

I just added one test branch with customized torch install location by set system env variable TORCH_INSTALL.
Can anyone test this branch https://github.com/imodpasteur/lutorpy/tree/detect-torch ? @korymath @kemelmi 

```
git clone https://github.com/imodpasteur/lutorpy.git
git checkout detect-torch
export TORCH_INSTALL = path/to/your/torch/install
python setup.py install
```

**Comment by korymath** [comment]
Seems to build nice, but the Lua runtime still doesn't want to start. 

((rllab)) [tw-mbp-kmathewson lutorpy]$ sudo python setup.py install
Password:
('torch_install:', '/Users/kmathewson/torch/install')
('os family', 'Darwin')
building without Cython
torch install:/Users/kmathewson/torch/install
running install
running bdist_egg
running egg_info
writing requirements to lutorpy.egg-info/requires.txt
writing lutorpy.egg-info/PKG-INFO
writing top-level names to lutorpy.egg-info/top_level.txt
writing dependency_links to lutorpy.egg-info/dependency_links.txt
reading manifest file 'lutorpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGES.rst'
warning: no files found matching 'INSTALL.rst'
warning: no files found matching 'README.rst'
writing manifest file 'lutorpy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
copying lutorpy/**init**.py -> build/lib.macosx-10.5-x86_64-2.7/lutorpy
copying lutorpy/torch_path.py -> build/lib.macosx-10.5-x86_64-2.7/lutorpy
copying lutorpy/version.py -> build/lib.macosx-10.5-x86_64-2.7/lutorpy
running build_ext
creating build/bdist.macosx-10.5-x86_64/egg
creating build/bdist.macosx-10.5-x86_64/egg/lutorpy
copying build/lib.macosx-10.5-x86_64-2.7/lutorpy/**init**.py -> build/bdist.macosx-10.5-x86_64/egg/lutorpy
copying build/lib.macosx-10.5-x86_64-2.7/lutorpy/_lupa.so -> build/bdist.macosx-10.5-x86_64/egg/lutorpy
copying build/lib.macosx-10.5-x86_64-2.7/lutorpy/torch_path.py -> build/bdist.macosx-10.5-x86_64/egg/lutorpy
copying build/lib.macosx-10.5-x86_64-2.7/lutorpy/version.py -> build/bdist.macosx-10.5-x86_64/egg/lutorpy
byte-compiling build/bdist.macosx-10.5-x86_64/egg/lutorpy/__init__.py to **init**.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/lutorpy/torch_path.py to torch_path.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/lutorpy/version.py to version.pyc
creating stub loader for lutorpy/_lupa.so
byte-compiling build/bdist.macosx-10.5-x86_64/egg/lutorpy/_lupa.py to _lupa.pyc
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying lutorpy.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying lutorpy.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying lutorpy.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying lutorpy.egg-info/not-zip-safe -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying lutorpy.egg-info/requires.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying lutorpy.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg
removing '/Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg' (and everything under it)
creating /Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg
Extracting lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg to /Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages
lutorpy 1.3 is already the active version in easy-install.pth

Installed /Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg
Processing dependencies for lutorpy==1.3
Searching for future==0.15.2
Best match: future 0.15.2
Processing future-0.15.2-py2.7.egg
future 0.15.2 is already the active version in easy-install.pth
Installing pasteurize script to /Users/kmathewson/anaconda/envs/rllab/bin
Installing futurize script to /Users/kmathewson/anaconda/envs/rllab/bin

Using /Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages/future-0.15.2-py2.7.egg
Searching for numpy==1.11.1
Best match: numpy 1.11.1
Adding numpy 1.11.1 to easy-install.pth file

Using /Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages
Finished processing dependencies for lutorpy==1.3
((rllab)) [tw-mbp-kmathewson lutorpy]$ cd ..
((rllab)) [tw-mbp-kmathewson cortex-testing]$ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, Oct 19 2015, 18:31:17) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

> > > import lutorpy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg/lutorpy/**init**.py", line 71, in <module>
> > >     LuaRuntime()
> > >   File "/Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg/lutorpy/**init**.py", line 68, in LuaRuntime
> > >     luaRuntime = lutorpy._lupa.LuaRuntime(_args, *_kwargs)
> > >   File "lutorpy/_lupa.pyx", line 231, in lutorpy._lupa.LuaRuntime.__cinit__ (lutorpy/_lupa.c:4642)
> > > lutorpy._lupa.LuaError: Failed to initialise Lua runtime

**Comment by oeway** [comment]
Thanks for your report @korymath , it seems you have another problem, could you try to install [lupa](https://github.com/scoder/lupa), and see if you have the same problem.

**Comment by korymath** [comment]
Yes, running into issues installing lupa as well.

On Tue, Jun 28, 2016 at 4:03 PM, Wei Ouyang notifications@github.com
wrote:

> Thanks for your report @korymath https://github.com/korymath , it seems
> you have another problem, could you try to install lupa
> https://github.com/scoder/lupa, and see if you have the same problem.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/imodpasteur/lutorpy/issues/8#issuecomment-229165842,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAK3szDKcpIUL6lKsP4dEWYyp34Fmjv4ks5qQX4vgaJpZM4I6PbU
> .

## 

---

Kory Mathewson

**Comment by oeway** [comment]
Then, I would encourage you try a clean up of your installation as
mentioned in the lupa issue.

**Comment by davidFMP** [comment]
I'm also experiencing this on Mac. I get the 'Failed to initialise Lua runtime' error:

Python 2.7.12 |Anaconda 4.1.1 (x86_64)| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

> > > import lutorpy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/davidfoster/anaconda2/envs/xo/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.6-x86_64.egg/lutorpy/**init**.py", line 71, in <module>
> > >     LuaRuntime()
> > >   File "/Users/davidfoster/anaconda2/envs/xo/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.6-x86_64.egg/lutorpy/**init**.py", line 68, in LuaRuntime
> > >     luaRuntime = lutorpy._lupa.LuaRuntime(_args, *_kwargs)
> > >   File "lutorpy/_lupa.pyx", line 231, in lutorpy._lupa.LuaRuntime.__cinit__ (lutorpy/_lupa.c:4642)
> > > lutorpy._lupa.LuaError: Failed to initialise Lua runtime

**Comment by davidFMP** [comment]
I have no problems installing lupa

**Comment by davidFMP** [comment]
I have no problems installing lupa though

Python 2.7.11 |Anaconda 4.1.0 (x86_64)| (default, Jun 15 2016, 16:09:16) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

> > > from lupa import LuaRuntime
> > > lua = LuaRuntime()
> > > 
> > > lua
> > >  lupa._lupa.LuaRuntime object at 0x1007906b0

**Comment by davidFMP** [comment]
When I run the import lutorpy command a second time, it gives me a different error

Python 2.7.11 |Anaconda 4.1.0 (x86_64)| (default, Jun 15 2016, 16:09:16) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

> > > import lutorpy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/davidfoster/anaconda2/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.6-x86_64.egg/lutorpy/**init**.py", line 72, in <module>
> > >     LuaRuntime()
> > >   File "/Users/davidfoster/anaconda2/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.6-x86_64.egg/lutorpy/**init**.py", line 69, in LuaRuntime
> > >     luaRuntime = lutorpy._lupa.LuaRuntime(_args, *_kwargs)
> > >   File "lutorpy/_lupa.pyx", line 231, in lutorpy._lupa.LuaRuntime.__cinit__ (lutorpy/_lupa.c:4642)
> > > lutorpy._lupa.LuaError: Failed to initialise Lua runtime
> > > 
> > > import lutorpy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/davidfoster/anaconda2/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.6-x86_64.egg/lutorpy/**init**.py", line 72, in <module>
> > >     LuaRuntime()
> > >   File "/Users/davidfoster/anaconda2/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.6-x86_64.egg/lutorpy/**init**.py", line 69, in LuaRuntime
> > >     luaRuntime = lutorpy._lupa.LuaRuntime(_args, *_kwargs)
> > > AttributeError: 'module' object has no attribute '_lupa'

**Comment by oeway** [comment]
Hi @davidFMP and others, thanks for your report.

I managed to reproduce your error on a mac, but haven't manage to make it work yet. So the problem is luajit or python on 64-bit OSX net special flags during compilation.

I think you could try:
`ARCHFLAGS="-arch x86_64" python setup.py install --no-luajit`

Or look at other solutions mentioned here: http://stackoverflow.com/questions/14657821/how-to-use-lua-with-python-on-mac-os-mountain-lion

**Comment by davidFMP** [comment]
OK I'll give that a go - I'm installing lua through torch, so would I need to specify the ARCHFLAGS line in the torch installation or just for lutorpy?

**Comment by davidFMP** [comment]
I tried installing with the line you recommended above and got a different error:

ARCHFLAGS="-arch x86_64" python setup.py install --no-luajit
No local build of LuaJIT2 found in lutorpy directory
Checking for installed lua5.2 library using pkg-config
pkg-config found lua5.2 version 5.2.4

building without Cython
running install
running bdist_egg
running egg_info
creating lutorpy.egg-info
writing requirements to lutorpy.egg-info/requires.txt
writing lutorpy.egg-info/PKG-INFO
writing top-level names to lutorpy.egg-info/top_level.txt
writing dependency_links to lutorpy.egg-info/dependency_links.txt
writing manifest file 'lutorpy.egg-info/SOURCES.txt'
reading manifest file 'lutorpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGES.rst'
warning: no files found matching 'INSTALL.rst'
warning: no files found matching 'README.rst'
writing manifest file 'lutorpy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.6-x86_64-2.7
creating build/lib.macosx-10.6-x86_64-2.7/lutorpy
copying lutorpy/**init**.py -> build/lib.macosx-10.6-x86_64-2.7/lutorpy
copying lutorpy/version.py -> build/lib.macosx-10.6-x86_64-2.7/lutorpy
running build_ext
building 'lutorpy._lupa' extension
creating build/temp.macosx-10.6-x86_64-2.7
creating build/temp.macosx-10.6-x86_64-2.7/lutorpy
gcc -fno-strict-aliasing -I/Users/davidfoster/anaconda2/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -DLUA_COMPAT_ALL -I/usr/local/Cellar/lua/5.2.4_3/include -I/Users/davidfoster/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/Users/davidfoster/anaconda2/include/python2.7 -c lutorpy/_lupa.c -o build/temp.macosx-10.6-x86_64-2.7/lutorpy/_lupa.o
lutorpy/_lupa.c:307:10: fatal error: 'THTensor.h' file not found
#include "THTensor.h"
         ^
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by korymath** [comment]
Okay, so it seems like I have gotten up to the problem being with lutorpy.

I can install and import lupa no problem... can build with cython, luajit

python setup.py install --with-cython 

I can not install and import lutorpy 

python setup.py install --with-cython

I think there is a problem with the setup.py of lutorpy... but I do not seem to be able to 

(rllab) [tw-mbp-kmathewson lutorpy]$ sudo python setup.py install --with-cython
Password:
found LuaJIT build in /Users/kmathewson/workspace/cortex-testing/lutorpy/LuaJIT-2.0.4/src
building statically
building with Cython 0.24
missing cimport in module 'lutorpy': lutorpy/_lupa.pyx
running install
running bdist_egg
running egg_info
writing requirements to lutorpy.egg-info/requires.txt
writing lutorpy.egg-info/PKG-INFO
writing top-level names to lutorpy.egg-info/top_level.txt
writing dependency_links to lutorpy.egg-info/dependency_links.txt
reading manifest file 'lutorpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGES.rst'
warning: no files found matching 'INSTALL.rst'
warning: no files found matching 'README.rst'
writing manifest file 'lutorpy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
copying lutorpy/version.py -> build/lib.macosx-10.5-x86_64-2.7/lutorpy
running build_ext
building 'lutorpy._lupa' extension
gcc -fno-strict-aliasing -I/Users/kmathewson/anaconda/envs/rllab/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DLUA_COMPAT_ALL -I/Users/kmathewson/workspace/cortex-testing/lutorpy/LuaJIT-2.0.4/src -I/Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages/numpy/core/include -I/Users/kmathewson/anaconda/envs/rllab/include/python2.7 -c lutorpy/_lupa.c -o build/temp.macosx-10.5-x86_64-2.7/lutorpy/_lupa.o
lutorpy/_lupa.c:307:10: fatal error: 'THTensor.h' file not found
#include "THTensor.h"
         ^
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by tuanfeng** [comment]
I've experienced the same error

> > > import lutorpy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/tuanfeng/anaconda/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg/lutorpy/**init**.py", line 72, in <module>
> > >     LuaRuntime()
> > >   File "/Users/tuanfeng/anaconda/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg/lutorpy/**init**.py", line 69, in LuaRuntime
> > >     luaRuntime = lutorpy._lupa.LuaRuntime(_args, *_kwargs)
> > >   File "lutorpy/_lupa.pyx", line 231, in lutorpy._lupa.LuaRuntime.__cinit__ (lutorpy/_lupa.c:4642)
> > > lutorpy._lupa.LuaError: Failed to initialise Lua runtime
> > > import lutorpy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/tuanfeng/anaconda/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg/lutorpy/__init__.py", line 72, in <module>
> > >     LuaRuntime()
> > >   File "/Users/tuanfeng/anaconda/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg/lutorpy/**init**.py", line 69, in LuaRuntime
> > >     luaRuntime = lutorpy._lupa.LuaRuntime(_args, *_kwargs)
> > > AttributeError: 'module' object has no attribute '_lupa'

**Comment by davidFMP** [comment]
@tuanfeng That's probably due to the fact you're running python in the same directory as lutorpy (there's a folder called lutorpy so it tries to import from here instead). Try running python from outside the lutorpy directory.
